#!/usr/bin/env ruby

$: << "File.dirname(__FILE__)/../lib"

require "contracts"

class Foo
  include Contracts

  +Returns(3)
  def r(x)
    x
  end

  +Expects(a: 1)
  +Returns(Array)
  def f(a, b, c)
    [ a, b, c]
  end
  
  +Expects(one: 1)
  def self.klass_method(one)
    one * 2
  end
end

p Foo.singleton_class
#.name

puts Contracts.current_contracts.count
puts Foo.klass_method 1
puts Foo.klass_method 2

puts "fini"

foo = Foo.new

foo.r(3)
foo.r(1)

foo.f(1,3,4)
foo.f(2,2,3)

# foo.f(1)        # scripts/test:67:in `f': wrong number of arguments (1 for 3) (ArgumentError)
